### ISSUE TITLE
Need access the response size

### ISSUE THREAD

**Issue by miekg** [miekg/caddy-prometheus#1]
I have no idea how to get the response size so we can export this.

**Comment by captncraig** [comment]
caddy has a `ResponseRecorder` type that can capture the status code and response size. https://github.com/mholt/caddy/blob/master/middleware/recorder.go#L17

Would be nice to capture raw throughput at the tcp layer rather than http, but bodies is what a middleware can do on its own.

**Comment by miekg** [comment]
oh, nice. That looks to be real easy to use, would also fix #5 (I think) 
 
Thanks!
