### ISSUE TITLE
Status code always responds 0 when using proxy.

### ISSUE THREAD

**Issue by rsanting** [miekg/caddy-prometheus#22]
When I use proxy in combination with prometheus monitorying I always get status=0

### Expected behaviour
Caddy returns the correct status code to prometheus. eg: 200 or 404 and so on.

### Actual behaviour

Caddy always returns status code 0

### Other info
config file is like this.

```
https://site.url.example 
{
    tls admin@example.net
    prometheus 0.0.0.0:9180
    proxy / localhost:3000 {
        websocket
        transparent
    }
 }

**Comment by miekg** [comment]
Yeah, it should not. But I probably don't have any time to work on this anytime soon.
