### ISSUE TITLE
publish plugin to new website

### ISSUE THREAD

**Issue by ulrichSchreiner** [miekg/caddy-prometheus#23]
hi,

your prometheus plugin needs a publish on the new caddy site to be available for 0.10. Without this the plugin cannot be downloaded for the 0.10 version of caddy.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/caddy-prometheus] publish pl..." ]
>hi,
>
>your prometheus plugin needs a publish on the new caddy site to be available for 0.10. Without this the plugin cannot be downloaded for the 0.10 version of caddy.

Ah, yeah, completely forgot :P

Done now.
