### ISSUE TITLE
Would it be possible to listen on the same port as Caddy itself?

### ISSUE THREAD

**Issue by hairyhenderson** [miekg/caddy-prometheus#30]
Obviously if we wanted Caddy to serve up another `/metrics` endpoint there'd be a conflict, but it'd be really useful if we only needed to expose a single port from Caddy for certain use-cases.

**Comment by miekg** [comment]
Currently not possible because this middleware adds its own handler. caddy-git listens for incoming webhooks from github on the default caddy port I think. So you might get some inspiration from there if you want to add this

**Comment by hairyhenderson** [comment]
Thanks @miekg for the pointer - I'll have a look at that!

**Comment by hairyhenderson** [comment]
@miekg this totally fell through the cracks - until today! 😉 I've proposed #35 to solve this.

**Comment by miekg** [comment]
Saw it. Thanks! Will take a look this evening.
