### ISSUE TITLE
Change Family tag to understandable values

### ISSUE THREAD

**Issue by genofire** [miekg/caddy-prometheus#46]
It should not be `"1"` and `"2"`.
For IPv4 it should be `"4"` and IPv6 should be `"6"`.
On this way, everybody understand those values.

Like everywhere, even the [IPvX-header](https://en.wikipedia.org/wiki/IPv6_packet) use the right value with his only four bits.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "[miekg/caddy-prometheus] Change Fam..." ]
>It should not be `"1"` and `"2"`.
>For IPv4 it should be `"4"` and IPv6 should be `"6"`.
>On this way, everybody understand those values.
>
>Like everywhere, even the [IPvX-header](https://en.wikipedia.org/wiki/IPv6_packet) use the right value with his only four bits.

the offical list is here: https://www.iana.org/assignments/address-family-numbers/address-family-numbers.xhtml

/Miek

--
Miek Gieben
